import { HttpClientModule } from '@angular/common/http';
import { NgModule } from '@angular/core';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';
import { MatSidenavModule } from '@angular/material/sidenav';
import { MatTableModule } from '@angular/material/table';
import { MatToolbarModule } from '@angular/material/toolbar';
import { BrowserModule } from '@angular/platform-browser';
import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
import { AppRoutingModule } from '@src/app/app-routing.module';
import { AppComponent } from '@src/app/app.component';
import { AutoGeneratedComponent } from '@src/app/auto-generated/auto-generated.component';
import { HabitListComponent } from '@src/app/habit-list/habit-list.component';
import { MainScreenComponent } from '@src/app/main-screen/main-screen.component';
import { MyListsComponent } from '@src/app/my-lists/my-lists.component';
import { SidenavService } from '@src/app/services/sidenav.service';

@NgModule({
  declarations: [
    AppComponent,
    MainScreenComponent,
    HabitListComponent,
    MyListsComponent,
    AutoGeneratedComponent,
  ],
  imports: [
    AppRoutingModule,
    BrowserAnimationsModule,
    BrowserModule,
    HttpClientModule,
    MatButtonModule,
    MatIconModule,
    MatSidenavModule,
    MatTableModule,
    MatToolbarModule,
    HttpClientModule,
  ],
  providers: [SidenavService],
  bootstrap: [AppComponent],
})
export class AppModule { }
